version: '3.8'

services:
  admin-healthy-menu:
    build: ./admin-healthy-menu
    ports:
      - "3001:80"  # внешний порт 3001 -> внутренний 80
    networks:
      - healthy-menu-network

  order-healthy-menu:
    build: ./order-healthy-menu
    ports:
      - "3002:80"  # внешний порт 3002 -> внутренний 80
    networks:
      - healthy-menu-network

  courier-healthy-menu:
    build: ./courier-healthy-menu
    ports:
      - "3003:80"  # внешний порт 3003 -> внутренний 80
    networks:
      - healthy-menu-network

networks:
  healthy-menu-network:
    driver: bridge
