services:
  # Backend services
  admin-backend:
    profiles: ["back_front"]
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  order-backend:
    profiles: ["back_front"]
    build:
      context: ./order-backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_healthy
    networks:
      - app-network

  courier-backend:
    profiles: ["back_front"]
    build:
      context: ./courier-backend
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - app-network

  # Frontend services
  admin-frontend:
    profiles: ["back_front"]
    build: ./admin-frontend
    ports:
      - "3001:80"
    networks:
      - app-network

  order-frontend:
    profiles: ["back_front"]
    build: ./order-frontend
    ports:
      - "3002:80"
    networks:
      - app-network

  courier-frontend:
    profiles: ["back_front"]
    build: ./courier-frontend
    ports:
      - "3003:80"
    networks:
      - app-network


  # Infra services
  postgres:
    profiles: ["infra"]
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  zookeeper:
    profiles: ["infra"]
    image: confluentinc/cp-zookeeper:latest
    restart: always
    env_file:
      - .env
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    profiles: ["infra"]
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    depends_on:
      - zookeeper
    env_file:
      - .env
    ports:
      - "9092:9092"
    networks:
      - app-network

  minio:
    profiles: ["infra"]
    image: quay.io/minio/minio:latest
    container_name: minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: ["server", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  createbuckets:
    profiles: ["infra"]
    image: quay.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      echo '$ /usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}';
      /usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/${MINIO_BUCKET} --ignore-existing;
      /usr/bin/mc anonymous set public minio/${MINIO_BUCKET};
      "
    networks:
      - app-network

  nexus:
    profiles: ["ci_cd"]
    image: sonatype/nexus3
    container_name: nexus
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  gitlab:
    profiles: ["ci_cd"]
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:8060'
        nginx['listen_port'] = 8060
        nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['allow_local_requests'] = true
    ports:
      - "8060:8060"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    healthcheck:
      disable: true
    networks:
      - app-network

  jenkins:
    profiles: ["ci_cd"]
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080
    networks:
      - app-network

  jenkins-agent:
    profiles: ["ci_cd"]
    container_name: jenkins-agent
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - agent_workdir:/home/jenkins/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /etc/hosts:/etc/hosts
    depends_on:
      - jenkins
    networks:
      - app-network

  postgres-sonar:
    profiles: ["ci_cd"]
    image: postgres:13-alpine
    container_name: postgres-sonar
    environment:
      POSTGRES_USER: ${SONAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SONAR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SONAR_POSTGRES_DB}
    volumes:
      - postgres_sonar_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SONAR_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  sonarqube:
    profiles: ["ci_cd"]
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      postgres-sonar:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonar:5432/${SONAR_POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_POSTGRES_PASSWORD}
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9009:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgres_data:
  minio_data:
  nexus_data:
  jenkins_home:
  agent_workdir:
  postgres_sonar_data:
  sonarqube_data:

networks:
  app-network:
    driver: bridge
