services:
  # Backend services
  admin-backend:
    profiles: ["back_front"]
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  order-backend:
    profiles: ["back_front"]
    build:
      context: ./order-backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_healthy
    networks:
      - app-network

  courier-backend:
    profiles: ["back_front"]
    build:
      context: ./courier-backend
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - app-network

  # Frontend services
  admin-frontend:
    profiles: ["back_front"]
    build: ./admin-frontend
    ports:
      - "3001:80"
    networks:
      - app-network

  order-frontend:
    profiles: ["back_front"]
    build: ./order-frontend
    ports:
      - "3002:80"
    networks:
      - app-network

  courier-frontend:
    profiles: ["back_front"]
    build: ./courier-frontend
    ports:
      - "3003:80"
    networks:
      - app-network


  # Infra services
  postgres:
    profiles: ["infra"]
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  zookeeper:
    profiles: ["infra"]
    image: confluentinc/cp-zookeeper:latest
    restart: always
    env_file:
      - .env
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    profiles: ["infra"]
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    depends_on:
      - zookeeper
    env_file:
      - .env
    ports:
      - "9092:9092"
    networks:
      - app-network

  minio:
    profiles: ["infra"]
    image: quay.io/minio/minio:latest
    container_name: minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data-minio:/data
    command: ["server", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  createbuckets:
    profiles: ["infra"]
    image: quay.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      echo '$ /usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}';
      /usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/${MINIO_BUCKET} --ignore-existing;
      /usr/bin/mc anonymous set public minio/${MINIO_BUCKET};
      "
    networks:
      - app-network

  nexus:
    profiles: ["ci_cd"]
    image: sonatype/nexus3
    container_name: nexus
    env_file:
      - .env
    ports:
      - "8082:8081"
      - "5001:5000"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 10s
      retries: 5

  gitlab:
    profiles: ["ci_cd"]
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:8061'
        nginx['listen_port'] = 8060
        nginx['listen_https'] = false
    ports:
      - "8061:8060"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    healthcheck:
      disable: true

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080" 
      - "50001:50000"  # Порт для запуска билдов
    volumes:
      - jenkins_home:/var/jenkins_home  # Постоянное хранилище данных Jenkins
    environment:
      JENKINS_OPTS: --httpPort=8080
    
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgres_data:
  data-minio:
  nexus-data:
  jenkins_home:

networks:
  app-network:
    driver: bridge




