# docker compose up -d --build
# docker compose --profile front_back up -d --build
# docker compose --profile front_back down
# или через переменную окружения:
# export COMPOSE_PROFILES=front_back
services:
  # Frontend services
  admin-frontend:
    profiles: ["front_back"]
    build: ./frontend/admin-healthy-menu
    ports:
      - "3001:80"
    networks:
      - healthy-menu-network

  order-frontend:
    profiles: ["front_back"]
    build: ./frontend/order-healthy-menu
    ports:
      - "3002:80"
    networks:
      - healthy-menu-network

  courier-frontend:
    profiles: ["front_back"]
    build: ./frontend/courier-healthy-menu
    ports:
      - "3003:80"
    networks:
      - healthy-menu-network

  # Backend services
  admin-backend:
    profiles: ["front_back"]
    build:
      context: ./backend
      dockerfile: admin/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthy-menu-network

  order-backend:
    profiles: ["front_back"]
    build:
      context: ./backend
      dockerfile: order/Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - healthy-menu-network

  courier-backend:
    profiles: ["front_back"]
    build:
      context: ./backend
      dockerfile: courier/Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - healthy-menu-network


  # Another services
  postgres:
    profiles: ["infra"]
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - healthy-menu-network

  zookeeper:
    profiles: ["infra"]
    image: confluentinc/cp-zookeeper:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "2181:2181"
    networks:
      - healthy-menu-network

  kafka:
    profiles: ["infra"]
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    depends_on:
      - zookeeper
    env_file:
      - ./backend/.env
    ports:
      - "9092:9092"
    networks:
      - healthy-menu-network

  minio:
    profiles: ["infra"]
    image: quay.io/minio/minio:latest
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data-minio:/data
    command: ["server", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  createbuckets:
    profiles: ["infra"]
    image: quay.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ./backend/.env
    entrypoint: >
      /bin/sh -c "
      echo '$ /usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}';
      /usr/bin/mc alias set minio http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/${MINIO_BUCKET};
      /usr/bin/mc anonymous set public minio/${MINIO_BUCKET};
      "

  nexus:
    profiles: ["ci_cd"]
    image: sonatype/nexus3
    container_name: nexus
    env_file:
      - ./backend/.env
    ports:
      - "8082:8081"
      - "5001:5000"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 10s
      retries: 5

  gitlab:
    profiles: ["ci_cd"]
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:8060'
        nginx['listen_port'] = 8060
        nginx['listen_https'] = false
    ports:
      - "8061:8060"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    healthcheck:
      disable: true
   
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgres_data:
  data-minio:
  nexus-data:

networks:
  healthy-menu-network:
    driver: bridge




