[project]
name = "migrations"
version = "0.1.0"
description = "Migration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.1",
    "black>=25.12.0",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.11",
]
