apiVersion: v1
kind: ConfigMap
metadata:
  name: courier-backend-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "healthy-menu"
  # or get ip - kubectl run -it --rm --restart=Never test-dns --image=busybox -- nslookup host.minikube.internal
  KAFKA_BOOTSTRAP_SERVERS: "host.minikube.internal:9092"
    # Важно: URL для Redis должен указывать на Service redis:6379
  REDIS_URL: "redis://redis:6379" # Используем имя Service redis

