apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: healthy-menu-gateway
  namespace: healthy-menu-dev
spec:
  selector:
    istio: ingressgateway   # стандартный istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - healthy-menu.local

