apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthy-menu-frontend-ingress
  namespace: healthy-menu-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: healthy-menu.local
    http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin-frontend
            port:
              number: 80
      - path: /order(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: order-frontend
            port:
              number: 80
      - path: /courier(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: courier-frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthy-menu-api-ingress
  namespace: healthy-menu-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: healthy-menu.local
    http:
      paths:
      - path: /api/v1/admin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin-backend
            port:
              number: 8000
      - path: /api/v1/order(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: order-backend
            port:
              number: 8000
      - path: /api/v1/courier(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: courier-backend
            port:
              number: 8000

