apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  # namespace: storage # TODO on prode
type: Opaque
data:
  # Здесь должны быть base64 закодированные значения
  # Пример: echo -n 'myuser' | base64
  # Подставьте свои значения из .env
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_HOST: host.minikube.internal
  MINIO_PORT: "9000"

