apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1czo1MDAwIjp7InVzZXJuYW1lIjoib3N0YXBrb2IiLCJwYXNzd29yZCI6InN1cGVycGFzczEyMyIsImVtYWlsIjoiYW55QGV4YW1wbGUuY29tIiwiYXV0aCI6ImIzTjBZWEJyYjJJNmMzVndaWEp3WVhOek1USXoifX19
metadata:
  name: nexus-creds
type: kubernetes.io/dockerconfigjson
