apiVersion: v1
kind: ConfigMap
metadata:
  name: order-backend-config
data:
  POSTGRES_HOST: postgres # Имя Service PostgreSQL
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "healthy-menu" # Замените на ваше имя БД из .env
  # Замените HOST_IP на реальный IP вашего хоста или используйте host.minikube.internal
  KAFKA_BOOTSTRAP_SERVERS: "host.minikube.internal:9092"
