---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-frontend
  template:
    metadata:
      labels:
        app: order-frontend
    spec:
      containers:
      - name: order-frontend
        image: host.minikube.internal:5000/order-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-frontend
spec:
  selector:
    app: order-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # NodePort позволяет получить доступ снаружи Minikube
      # Kubernetes сам назначит порт в диапазоне 30000-32767
      nodePort: 30002
  type: NodePort
