apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Здесь должны быть base64 закодированные значения
  # Пример: echo -n 'myuser' | base64
  # Подставьте свои значения из .env
  POSTGRES_USER: cG9zdGdyZXM= # Замените на результат echo -n 'your_actual_user' | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Замените на результат echo -n 'your_actual_password' | base64
  POSTGRES_DB: cG9zdGdyZXM= # Замените на результат echo -n 'your_actual_db' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_HOST: host.minikube.internal
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "food_db"
