apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-backend
  template:
    metadata:
      labels:
        app: admin-backend
    spec:
      containers:
      - name: admin-backend
        image: localhost:5000/admin-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
