---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets: 
         - name: nexus-creds 
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}/{{ .Release.Name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        # Postgres
        # Загружаем переменные из ConfigMap
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.postgres.configMap }}
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.postgres.configMap }}
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.postgres.configMap }}
              key: POSTGRES_DB
        # Загружаем чувствительные переменные из Secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.postgres.secret }}
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.postgres.secret }}
              key: POSTGRES_PASSWORD
        # Формируем DATABASE_URL через args
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"

        # MINIO
        - name: MINIO_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.minio.configMap }}
              key: MINIO_HOST
        - name: MINIO_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.minio.configMap }}
              key: MINIO_PORT
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.minio.secret }}
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.minio.secret }}
              key: MINIO_ROOT_PASSWORD

        # KAFKA
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.kafka.configMap }}
              key: KAFKA_BOOTSTRAP_SERVERS
